name: Deploy

on:
  push:
    branches:
      - gh-pages
  # TMP
  pull_request:
  workflow_dispatch:

jobs:
  Deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: true
          ref: gh-pages

      -   name: Setup SSH Keys and known_hosts
          env:
            SSH_AUTH_SOCK: /tmp/ssh_agent.sock
          run: |
            ssh-agent -a $SSH_AUTH_SOCK > /dev/null
            ssh-add - <<< "${{ secrets.JULIADATASCIENCE }}"

      - name: Deploy to JuliaDataScience
        shell: julia --color=yes {0}
        run: |
          jds_dir = mktempdir()
          secret = ENV["JULIADATASCIENCE"]
          url = "https://github.com/JuliaDataScience/JuliaDataScience"
          run(`git clone --branch=gh-pages $url $jds_dir`)
          from = "."
          to = joinpath(jds_dir, "pt")
          mkpath(to)
          cp(from, to; force=true)
          cd(jds_dir) do
              run(`git add .`)
              run(`git config --global user.email 'contact@juliadatascience.io'`)
              run(`git config --global user.name 'Bot'`)
              run(`git commit -m 'deploy from JuliaDataScience-PT'`)
              run(`git push`)
          end

