name: Deploy

on:
  push:
    branches:
      - gh-pages
  # TMP
  pull_request:
  workflow_dispatch:

jobs:
  Deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          ref: gh-pages

      - name: Deploy to JuliaDataScience
        run: julia src/push-jds.jl

